//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectQuantity
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public int ItemID { get; set; }
        public string Location { get; set; }
        public int Status { get; set; }
        public decimal Quantity { get; set; }
        public string WorkDescription { get; set; }
        public string ImageNote { get; set; }
        public string ImageFilePath { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ProjectReport ProjectReport { get; set; }
    }
}
