//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectReport()
        {
            this.ProjectLabourEquipments = new HashSet<ProjectLabourEquipment>();
            this.ProjectQuantities = new HashSet<ProjectQuantity>();
        }
    
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string ReportNumber { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string MorningWeather { get; set; }
        public string EveningWeather { get; set; }
        public decimal MorningTemprature { get; set; }
        public decimal EveningTemperature { get; set; }
        public int InspectedBy { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public int CheckedBy { get; set; }
        public System.DateTime CheckedDate { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectLabourEquipment> ProjectLabourEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectQuantity> ProjectQuantities { get; set; }
    }
}
