//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLabourEquipment
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public string ContractorName { get; set; }
        public string Labour_Name { get; set; }
        public string EquipmentName { get; set; }
        public string WorkDescription { get; set; }
        public Nullable<decimal> LabourHours { get; set; }
        public Nullable<decimal> EquipmentHours { get; set; }
    
        public virtual ProjectReport ProjectReport { get; set; }
    }
}
