//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordActivation
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public System.Guid PasswordActivattionKey { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsExpired { get; set; }
    
        public virtual User1 User { get; set; }
    }
}
